name: Update Homebrew Tap

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-easy-checkout
        uses: actions/checkout@v4
        with:
          repository: m44rten1/homebrew-easy-checkout
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Get latest tag
        id: get_tag
        run: echo "tag_name=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Download new release binaries
        run: |
          wget https://github.com/m44rten1/easy-checkout/releases/download/${{ steps.get_tag.outputs.tag_name }}/easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-amd64
          wget https://github.com/m44rten1/easy-checkout/releases/download/${{ steps.get_tag.outputs.tag_name }}/easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-arm64
          sha256sum easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-amd64 > checksum_amd64.txt
          sha256sum easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-arm64 > checksum_arm64.txt

      - name: Update formula
        run: |
          cd homebrew-tap
          # Update AMD64 url and sha256
          sed -i "s|url \"https://github.com/m44rten1/easy-checkout/releases/download/v.*-darwin-amd64\"|url \"https://github.com/m44rten1/easy-checkout/releases/download/${{ steps.get_tag.outputs.tag_name }}/easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-amd64\"|" easy-checkout.rb
          NEW_SHA_AMD64=$(cut -d' ' -f1 ../checksum_amd64.txt)
          sed -i "s|sha256 \"[a-f0-9]\{64\}\"|sha256 \"$NEW_SHA_AMD64\"|" easy-checkout.rb
          # Update ARM url and sha256
          sed -i "s|url \"https://github.com/m44rten1/easy-checkout/releases/download/v.*-darwin-arm64\"|url \"https://github.com/m44rten1/easy-checkout/releases/download/${{ steps.get_tag.outputs.tag_name }}/easy-checkout-${{ steps.get_tag.outputs.tag_name }}-darwin-arm64\"|" easy-checkout.rb
          NEW_SHA_ARM64=$(cut -d' ' -f1 ../checksum_arm64.txt)
          sed -i "0,/sha256 \"[a-f0-9]\{64\}\"/s//sha256 \"$NEW_SHA_ARM64\"/" easy-checkout.rb
          # Update version
          sed -i "s|version \".*\"|version \"${{ steps.get_tag.outputs.tag_name }}\"|" easy-checkout.rb

      - name: Commit and push
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add easy-checkout.rb
          git commit -m "Update to ${{ steps.get_tag.outputs.tag_name }}"
          git push
